### ISSUE TITLE
ModuleNotFoundError: No module named 'networks.relay_net'

### ISSUE THREAD

**Issue by gelazari** [abhi4ssj/relaynet_pytorch#11]
I'm getting the following error when trying to load a pretrained model. 

model = torch.load('path/to/model/relaynet_epoch20.model')

Traceback (most recent call last):
  File "C:\Users\gelaz\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-da10b9c7e475>", line 1, in <module>
    relaynet_model =  torch.load(r'C:\Users\gelaz\PycharmProjects\VariationalOptimization\relaynet_pytorch\models\Exp01/relaynet_epoch20.model')
  File "C:\Users\gelaz\Anaconda3\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\gelaz\Anaconda3\lib\site-packages\torch\serialization.py", line 538, in _load
    result = unpickler.load()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'networks.relay_net'

**Comment by cloudstaymoon** [comment]
Have you solved this problem? Today, I encountered this problem too when I used this model.

**Comment by hwei-hw** [comment]
you should rename the directory "relaynet_pytorch" to "networks" !

**Comment by qwertyuiop194** [comment]
> you should rename the directory "relaynet_pytorch" to "networks" !

I did this, it didn't work.

**Comment by yuanleilei12138** [comment]
> > you should rename the directory "relaynet_pytorch" to "networks" !
> 
> I did this, it didn't work.

sorry, have you solved the problem yet? I encoutered this problem too. I look forward to your reply sincerely.
